# Generated by Django 3.2.24 on 2024-08-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('views', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
